do $$
begin
  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'admin_users'
  ) then
    create table public.admin_users (
      id bigint generated by default as identity primary key,
      login text not null unique,
      email text,
      password_hash text not null,
      role text not null default 'operator' check (role in ('super_admin', 'operator', 'finance', 'viewer')),
      is_active boolean not null default true,
      created_at timestamptz not null default timezone('utc', now()),
      last_login_at timestamptz
    );
  end if;
end$$;

create unique index if not exists idx_admin_users_single_super_admin
on public.admin_users ((role))
where role = 'super_admin';

create index if not exists idx_admin_users_login on public.admin_users (login);

create table if not exists public.admin_sessions (
  token_hash text primary key,
  admin_user_id bigint not null references public.admin_users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default timezone('utc', now()),
  user_agent text,
  ip text
);

create index if not exists idx_admin_sessions_user on public.admin_sessions (admin_user_id);
create index if not exists idx_admin_sessions_expires_at on public.admin_sessions (expires_at);


alter table public.admin_users add column if not exists email text;
create unique index if not exists idx_admin_users_email_lower on public.admin_users (lower(email)) where email is not null;
